apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: stonesoup-pr-quota-controller
    newName: pipelinerun-quota-controller-image
    newTag: dev
