apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: stonesoup-pr-quota-controller
    newName: quay.io/gabemontero/stonesoup-pipelinerun-quota-controller
    newTag: dev
